title: Blog | Gustavo Siebra
description: This blog about programming, data science, civil engineering. # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: #"/flexible-jekyll" # the subpath of your site, e.g. /blog
url: #"https://gustavosiebra.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gustavo Siebra # add your name
author-img: foto.jpeg # add your photo
about-author: Engenheiro civil # add description
social-github: gustavosiebra # add your Github handle
social-linkedin: gustavosiebra # add your Linkedin handle
social-twitter: gustavosiebra # add your Twitter handle
social-youtube: gustavosiebra # add your Youtube handle
#social-facebook: gustavosiebra # add your Facebook handle
social-email: gustavosiebra@gmail.com # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: UA-165697389-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
